name: geoesplora
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true,
  fonts:
   -family: Axiforma
    fonts: 
     -asset: assets/fonts/Axiforma-Regular.ttf
      weight: 400
    fonts:
      -asset: assets/fonts/Axiforma-Bold.ttf
       weight: 700
    fonts:
      -asset: assets/fonts/Axiforma-Light.ttf
       weight: 400
